description: This is a template researchers can walk away with and create their own Portfolio.
datelastupdated: 25 Nov 2021
fullnameofperson: Emily Pickering
selfIdentification: PhD candidate and Complementary Medicine Practitioner
colour1: "#8C1A6A"  # sidebar background 
colour2: "#a3cef1"  # colour of name and desc
colour3: "#a3cef1"  # colour of Menu links
colour4: "#DFD3EE" # trying to be background colour 
colour5: "#DFD3EE" # menu link colour when hover - might be background colour
